---
session_name: nix
start_directory: "$HOME/nix-config"
windows:
  - panes:
      - shell: nvim
      - shell: flake watch
    options:
      other-pane-width: 80
      remain-on-exit: true
    layout: main-vertical
  - panes:
      - shell: "nix repl -f '<nixpkgs>'"
    layout: main-vertical
